version: "3.9"

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper
    environment:
      - NODE_ENV=production
      - SCRAPER_METRICS_PORT=9464
      # add your own envs for WSE, proxies, etc:
      # - BRIGHTDATA_WSE_URL=wss://brd.superproxy.io:9222?token=...
      # - PUPPETEER_DEBUG=1
    ports:
      - "9464:9464"           # expose /metrics to Prometheus
    volumes:
      - ./data:/app/data
      - ./session:/app/.session_data
      - ./.env:/app/.env:ro   # your secrets/config
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom_data:/prometheus
    depends_on:
      - scraper
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      # ✅ SMTP so Grafana can send emails
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mail.ryanhideosmtp.com:587
      - GF_SMTP_USER=alerts@ryanhideosmtp.com
      - GF_SMTP_PASSWORD=REPLACE_ME
      - GF_SMTP_FROM=alerts@ryanhideosmtp.com
      - GF_SMTP_STARTTLS_POLICY=OpportunisticStartTLS
    volumes:
      - ./grafana-provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana-provisioning/alerting:/etc/grafana/provisioning/alerting:ro
      - ./grafana-provisioning/plugins:/etc/grafana/provisioning/plugins:ro
    depends_on:
      - prometheus
    restart: unless-stopped
volumes:
  prom_data:
  grafana_data:
