# prometheus.yml
global:
  scrape_interval: 5s
  scrape_timeout: 4s

scrape_configs:
  - job_name: 'scraper'
    static_configs:
      - targets: ['scraper:9464']  # or 'scraper:9464' if you dockerize the scraper
